from .objs.account import Account
from .objs.auth import Authentication
from .objs.certification import Certification
from .objs.collection import Collection
from .objs.company import Company
from .objs.configuration import Configuration
from .objs.discover import Discover
from .objs.episode import Episode
from .objs.genre import Genre
from .objs.list import List
from .objs.movie import Movie
from .objs.person import Person
from .objs.season import Season
from .objs.tv import TV
from .tmdb import TMDb
